### ISSUE TITLE
Get n64/gcc2.8.1sn/cc1n64.exe running

### ISSUE THREAD

**Issue by evmar** [evmar/retrowin32#10]
n64/gcc2.8.1sn/cc1n64.exe comes from https://github.com/decompme/decomp.me and is some n64 compiler(?).

Currently it dies at

```
INFO win32/src/winapi/kernel32/misc.rs:194 kernel32/misc/GetVersion()
INFO win32/src/winapi/kernel32/memory.rs:282 kernel32/memory/HeapCreate(flOptions:Ok(HEAP_NO_SERIALIZE), dwInitialSize:1000, dwMaximumSize:0)
INFO win32/src/winapi/kernel32/memory.rs:350 kernel32/memory/VirtualAlloc(lpAddress:0, dwSize:400000, flAllocationType:Ok(RESERVE), flProtec:Ok(READWRITE))
INFO win32/src/winapi/kernel32/memory.rs:350 kernel32/memory/VirtualAlloc(lpAddress:1979000, dwSize:10000, flAllocationType:Ok(COMMIT), flProtec:Ok(READWRITE))
ERROR cli/src/main.rs:358 "oob at e80f9084"
00527aa0 c6460400   mov byte ptr [esi+4],0
```

Disassembling a bit that pointer appears to come from some sort of malloc implementation (my best guess).  It's asked to alloc 0x100 and it gets that big pointer back when it probably should get a pointer within the VirtualAlloc'd regions just above.

**Comment by evmar** [comment]
Running via Rosetta has a wholly different trace

```
WARN win32/src/winapi/kernel32/misc.rs:131 IsProcessorFeaturePresent(Ok(FLOATING_POINT_PRECISION_ERRATA)) => false
thread 'main' panicked at win32/src/shims_raw.rs:52:22:
not implemented: kernel32.dll:GetTimeZoneInformation
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Maybe it implements cpuid differently?  I haven't been able to use Rosetta much for debugging anything lately, since after a MacOS update when Rust panics like the above within Rosetta the process gets totally wedged in a way where I can't even kill it.

**Comment by evmar** [comment]
After tracing through this a bit, it seems like this is within the very first malloc, and the failure is somehow part of the initial boot of the c library's malloc implementation.  There's some `if (size < 0x1e0) foo() else HeapAlloc()` and we take the first branch, do a ton of work, and and come back with a garbage pointer, so I imagine there's some sort of small-object malloc helper that I'm somehow running wrong.

**Comment by evmar** [comment]
With the above fix the execution gets up to this point:

```
INFO win32/src/winapi/kernel32/file.rs:81 kernel32/file/CreateFileA(lpFileName:Some("blah.s"), dwDesiredAccess:40000000, dwShareMode:3, lpSecurityAttributes:f6f10, dwCreationDisposition:Err(2), dwFlagsAndAttributes:Ok(NORMAL), hTemplateFile:HANDLE(0))
thread 'main' panicked at win32/src/winapi/kernel32/file.rs:97:9:
not implemented: CreateFile access WRITE
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

which is to say, I hadn't supported file writing yet, hah.  I will try that next.

**Comment by evmar** [comment]
OK, main now successfully writes a file from this exe.  Something is wrong where it computes the wrong output filename and overwrites its input, but at least itdemonstrates successful end-to-end emulation with the relevant Windows API in place as well.

```
$ cargo run -p retrowin32 -F x86-emu -- exe/cc1n64.exe  "cc1n64.exe -o blah.o blah.s" |& grep -v unimpl
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/retrowin32 exe/cc1n64.exe 'cc1n64.exe -o blah.o blah.s'`
WARN win32/src/winapi/kernel32/misc.rs:131 IsProcessorFeaturePresent(Ok(FLOATING_POINT_PRECISION_ERRATA)) => false
<built-in>:0: warning: conflicting types for built-in function `__builtin_fabs'

time in parse: 0.000000
time in integration: 0.000000
time in jump: 0.000000
time in cse: 0.000000
time in loop: 0.000000
time in cse2: 0.000000
time in branch-prob: 0.000000
time in flow: 0.000000
time in combine: 0.000000
time in sched: 0.000000
time in local-alloc: 0.000000
time in global-alloc: 0.000000
time in sched2: 0.000000
time in dbranch: 0.000000
time in shorten-branch: 0.000000
time in stack-reg: 0.000000
time in final: 0.000000
time in varconst: 0.000000
time in symout: 0.000000
time in dump: 0.000000
963902 instrs in 61 ms: 15m/s
icache: 190475 hit, 6377 miss, 96% hit rate

$ cat blah.s
        .file   1 "blah.s"
gcc2_compiled.:
__gnu_compiled_c:
```

**Comment by evmar** [comment]
Ok, I think this almost works now with the example you gave:

```
$ cargo run -p retrowin32 -F x86-emu -- -- ./exe/cc1n64.exe 'cc1n64.exe -o blah.o blah.s' |& grep -v unimpl
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/retrowin32 -- ./exe/cc1n64.exe 'cc1n64.exe -o blah.o blah.s'`
WARN win32/src/winapi/kernel32/misc.rs:131 IsProcessorFeaturePresent(Ok(FLOATING_POINT_PRECISION_ERRATA)) => false
blah.s:1: `$' in identifier
blah.s:1: parse error before `$ra'

time in parse: 0.000000
[...]
```

Can you give me a more complex example to try?

(This was some pretty wild debugging, thanks for the target to investigate!)

**Comment by ethteck** [comment]
Yeah.. my bad, this was a stupid example because I tried to give a c compiler a .s file (with bad syntax) instead of a .c file without specifying the flag to assemble only. 

Also, thanks so much for working on this and getting this so far! I think just making sure we can get some reasonable output from a basic c file is the first step. so like

(input.h)
```c
#define SOMETHING 5
typedef unsigned char u8;
typedef unsigned long u32;
typedef long s32;
typedef float f32;
s32 auPlaySoundWithParams(u32 soundID, s32 volume, s32 pan, f32 pitch, s32 reverbAmt);
void auSetSoundVolume(s32 handle, u32 vol);
void auStopSound(u32 handle);
void func_803507E0_4F0BF0(s32);
extern u32 D_802D2A90_7AC020;
extern u32 D_802D2A94_7AC024;
extern u8 D_8034C8C8_825E58[];
```

(input.c)
```c
#include "input.h"

double stuff(int a) {
    return SOMETHING + (a / 5.0f);
}

void func_802C6B30_7A00C0(s32 arg0, f32 arg1) {
    switch (D_802D2A90_7AC020) {
        case 0:
            D_8034C8C8_825E58[0] = auPlaySoundWithParams(0x22, 0x3800, 0x40, 1.0f, 0x3C);
            D_802D2A90_7AC020 = 1;
            break;
        case 1:
            if ((arg0 + arg1) > 0.0f) {
                func_803507E0_4F0BF0(7);
                D_802D2A90_7AC020 = 3;
            }
            break;
        case 3:
            if (((arg0 + arg1) > 1.8f) && ((arg0 + arg1) < 2.05f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], (((arg0 + arg1) - 1.8f) * 6144.0f * 4.0f) + 14336.0f);
            } else if ((arg0 + arg1) >= 2.05f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x5000);
                D_802D2A90_7AC020 = 4;
            }
            break;
        case 4:
            if (((arg0 + arg1) > 3.0f) && ((arg0 + arg1) < 3.25f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], ((3.25f - (arg0 + arg1)) * 6144.0f * 4.0f) + 14336.0f);
            } else if ((arg0 + arg1) >= 3.25f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x3800);
                D_802D2A90_7AC020 = 5;
            }
            break;
        case 5:
            if (((arg0 + arg1) > 4.0f) && ((arg0 + arg1) < 4.25f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], (((arg0 + arg1) - 4.0f) * 6144.0f * 4.0f) + 14336.0f);
            } else if ((arg0 + arg1) >= 4.25f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x5000);
                D_802D2A90_7AC020 = 6;
            }
            break;
        case 6:
            if (((arg0 + arg1) > 4.58f) && ((arg0 + arg1) < 5.08f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], ((5.08f - (arg0 + arg1)) * 3072.0f * 2.0f) + 17408.0f);
            } else if ((arg0 + arg1) >= 5.08f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x4400);
                D_802D2A90_7AC020 = 7;
            }
            break;
        case 7:
            if (((arg0 + arg1) > 5.28f) && ((arg0 + arg1) < 5.53f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], (((arg0 + arg1) - 5.28f) * 3072.0f * 4.0f) + 17408.0f);
            } else if ((arg0 + arg1) >= 5.53f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x5000);
                D_802D2A90_7AC020 = 8;
            }
            break;
        case 8:
            if (((arg0 + arg1) > 5.95f) && ((arg0 + arg1) < 6.15f)) {
                auSetSoundVolume(D_8034C8C8_825E58[0], ((6.15f - (arg0 + arg1)) * 6144.0f * 5.0f) + 14336.0f);
            } else if ((arg0 + arg1) >= 6.15f) {
                auSetSoundVolume(D_8034C8C8_825E58[0], 0x3800);
                D_802D2A90_7AC020 = 9;
            }
            break;
        case 9:
        default:
            break;
    }
}
```

and then with flags `-O2 -o stuff.o stuff.c` should produce a valid object file

**Comment by evmar** [comment]
I get this output:
```
input.c:1: undefined or invalid # directive
 stuff
input.c: In function `stuff':
[...]
```

Confusingly, that is also what I get when I run the same command on Windows?

This is on WSL, so this is using native Windows to invoke the exe:
```
evmar@mara:~/decomp$ cat > demo.c
#include "testwtf.h"
evmar@mara:~/decomp$ n64/gcc2.8.1sn/cc1n64.exe -O2 -o stuff.o demo.c
demo.c:1: undefined or invalid # directive
```

**Comment by ethteck** [comment]
sorry...maybe this doesn't run the c preprocessor. I guess we can remove the #include and put the stuff directly in the c file

**Comment by evmar** [comment]
With the header inlined, this seems to generate a .o file containing assembly.  Is that what you expect?

**Comment by ethteck** [comment]
Yeah, it's my fault for not reading the name of the binary properly.. I thought this was the entire compiler driver, but it's just cc1, which explains why the preprocessor isn't running either. 

Anyway, I think this is working totally correctly! As far as I'm concerned, this can be closed and I'll open another issue for another binary in the future if that works :)

**Comment by evmar** [comment]
Sounds good, thanks for the useful test cases!
