### ISSUE TITLE
Getting PocoMan.exe running

### ISSUE THREAD

**Issue by LinusU** [evmar/retrowin32#43]
This issue is to track my work in getting [PocoMan v4.0](https://www.sleepless.com/pocoman/) running. See more background in #39 

My working branch is here: https://github.com/LinusU/retrowin32/tree/pocoman

- `kernel32.dll`
    - [x] `GetStartupInfoA` #40
    - [x] `SizeofResource` #42
    - [x] `SetEnvironmentVariableA` #44 
    - [x] `CreateEventA`/`SetEvent` #45
    - [x] `ResumeThread` #52
    - [x] `ExitThread` #56
    - [ ] `WideCharToMultiByte`    
- `advapi32.dll`
    - [x] `RegCreateKeyA`/`RegQueryValueExA` #41
    - [x] `RegSetValueExA` #48
- `ole32.dll`
    - [x] `OleInitialize` #46
- `user32.dll`
    - [x] `LoadMenuA` #47
    - [x] `GetWindowRect` #53
    - [x] `SetMenuItemInfoA` #54
    - [x] `GetWindowPlacement` #59 + #67
    - [x] `CreatePopupMenu` #60
    - [x] `GetSubMenu` #61
    - [x] `KillTimer` #63
    - [x] `SetWindowPos` #69
- `gdi32.dll`
    - [x] null `hdcSrc` with `BLACKNESS` #50
    - [x] `CreatePalette` #68
    - [x] `SelectPalette`/`RealizePalette` #49
    - [x] `SetTextAlign` #66
- `wininet32.dll`
    - [x] `InternetOpenA` #51
- Instructions
    - [x] `imul_r16_rm16` #55
- General
    - [x] Stretched blitting
    - [x] Flipped blitting
    - [ ] Keyboard input

**Comment by evmar** [comment]
This looks great so far, thanks for breaking it up!  Also if you need any help or advice looking into your binary please reach out. I would love to flesh out the docs with anything useful for you.

**Comment by evmar** [comment]
By the way, if a function is missing, retrowin32 logs a warning about it but keeps running.  So it will only matter if your binary actually calls it (where it will crash after calling a null pointer).  Functions like ExitThread might not matter until you get to the end of the program, not sure.

**Comment by LinusU** [comment]
It seems like the threading is just used to kick of one thread that connects to the internet and check some kind of latest news, stores it in the registry, and then exits. Without `ExitThread` it crashed the entire program when it tried to exit, which since I've only stubbed the internet connect functions is basically immediately 😅 

I'm at a point now where the program can run more than a few milliseconds! Unfortunately, it's a very tiny window, and something with the rendering seems broken. And as soon as I press anywhere it tries to call `WideCharToMultiByte`.

<img width="176" alt="Screenshot 2024-09-14 at 23 30 00" src="https://github.com/user-attachments/assets/c5268654-9547-4cb2-a981-4744fcf69228">

```
INFO win32/src/winapi/user32/window.rs:324 user32/window/CreateWindowExA(dwExStyle:Err(300), lpClassName:Name("PocoMan Class"), lpWindowName:Some("PocoMan"), dwStyle:Ok(BORDER | DLGFRAME | SYSMENU | GROUP), X:80000000, Y:0, nWidth:1, nHeight:1, hWndParent:HANDLE(0), hMenu:0, hInstance:400000, lpParam:0) -> HANDLE(1)
```

This part seems a bit suspicious: `X:80000000, Y:0, nWidth:1, nHeight:1`

**Comment by evmar** [comment]
One idea is you could maybe locally stub out the CreateThread impl such that it never starts the thread in the first place, just to see what happens next.  Depends on if it waits for the thread to come back though.  I saw in your above list you had CreateEvent/SetEvent which are typically used for thread synchronization...

I ran the installer (via wine 😊 ) and I get this:

```
     Running `target/debug/retrowin32 --win32-trace - '/Users/evmar/.wine/drive_c/Program Files (x86)/PocoMan/pocoman.exe'`
WARN win32/src/winapi/kernel32/dll.rs:216 load_library("wsock32.dll"): not found
WARN win32/src/winapi/kernel32/misc.rs:152 IsProcessorFeaturePresent(Ok(FLOATING_POINT_PRECISION_ERRATA)) => false
thread 'main' panicked at x86/src/ops/basic.rs:478:16:
attempt to shift left with overflow
```


The window size could indicate a problem, but also some apps I've seen create a window with an unknown size, then resize it later in response to some window messages.
... since I have the exe anyway I checked and that is what it does.

ghidra says:
```
      g_hwnd = CreateWindowExA(0x300,s_PocoMan_Class_00418174,s_PocoMan_00418184,0xca0000,local_14,
                               local_18,1,1,(HWND)0x0,(HMENU)0x0,pHVar2,(LPVOID)0x0);
```
and there is some function called by the wndproc that does

```
  GetWindowRect(g_hwnd,&local_3c);
  GetClientRect(g_hwnd,&tStack_4c);
  SetWindowPos(g_hwnd,(HWND)0x0,0,0, ...
```

**Comment by evmar** [comment]
My above crash is fixed in 6427aededc6dc4e161b2ad9a93788af3e342e0c5, which now reveals the actual problem was running from the wrong directory

```
MessageBox: PocoMan
Can't open PocoMan.map for reading
```

**Comment by LinusU** [comment]
Sorry, I have had limited with time today and just cherry picked som already done work. Will give some more time to the comments later!

> If it helps you any, feel free to send a PR that is just like "here are all the stubs I need"

Hehe, yeah I realized that that would probably have been a good strategy 😅 

At this point I think that they are all merged though! Well, as far as I have gotten at least, will probably be a bit more when I get more time to dig further!

Thanks for all the help, and for looking into the binary yourself! As said, I'll try to read thru all your comments properly and answer in a few days

**Comment by LinusU** [comment]
Making progress!

<img width="1143" alt="Screenshot 2024-09-22 at 17 19 28" src="https://github.com/user-attachments/assets/5063016c-8c92-41d2-a238-f21d5ee66d2f">

Updating `SetWindowPos` to actually resize the host window fixed the sizing issue!

Need to implement stretching in `StretchBlt` now 🐎

**Comment by LinusU** [comment]
I'm running into a really strange problem. For some reason, the application is closing its file handle whilst in the middle of reading from it. It's reading the map data, and since it then errors out goes into an error state. Making `CloseHandle` a no-op fixes the issue:

```diff
diff --git a/win32/src/winapi/kernel32/file.rs b/win32/src/winapi/kernel32/file.rs
index 79e7b8a1..c8a6946f 100644
--- a/win32/src/winapi/kernel32/file.rs
+++ b/win32/src/winapi/kernel32/file.rs
@@ -382,7 +382,7 @@ pub fn SetFilePointer(
         lDistanceToMove |= (**high as i64) << 32;
     }
     let Some(file) = machine.state.kernel32.files.get_mut(hFile) else {
-        log::debug!("SetFilePointer({hFile:?}) unknown handle");
+        log::warn!("SetFilePointer({hFile:?}) unknown handle");
         set_last_error(machine, ERROR_INVALID_HANDLE);
         return u32::MAX;
     };
diff --git a/win32/src/winapi/kernel32/misc.rs b/win32/src/winapi/kernel32/misc.rs
index d6d06472..49de0c85 100644
--- a/win32/src/winapi/kernel32/misc.rs
+++ b/win32/src/winapi/kernel32/misc.rs
@@ -279,6 +279,7 @@ pub fn FormatMessageW(
 
 #[win32_derive::dllexport]
 pub fn CloseHandle(machine: &mut Machine, hObject: HFILE) -> bool {
+    return true; // FIXME: remove this line
     if machine.state.kernel32.files.remove(hObject).is_none() {
         log::debug!("CloseHandle({hObject:?}): unknown handle");
         set_last_error(machine, ERROR_INVALID_HANDLE);

```

It's happening right after the call to `InternetOpenA`, which I think is called by a background thread. I'm wondering if the file handles are somehow interfering with each other from the different threads 🤔 

Reading the disassembled source, there are calls to `InternetCloseHandle` at the end of the function that runs in the background thread...

**Comment by LinusU** [comment]
With the `CloseHandle` patch from last comment, the first map now loads! 🙌 

<img width="752" alt="Screenshot 2024-09-22 at 19 06 40" src="https://github.com/user-attachments/assets/1e1dc6d1-96a9-495a-b660-0c05f35d1be6">

**Comment by evmar** [comment]
Re time, I just monkeyed with it here, maybe I got something wrong: https://github.com/evmar/retrowin32/commit/0c3e48507dc5f6424d5b10b6e230046a4c2095cd

Re CloseHandle, I looked at the places where it's called in pocoman and most seemed to be error paths.  But the one at address 00410419 might be it(?).

I wrote all of the threading-related stubs before retrowin32 supported threads so they are all definitely wrong.  I see some use of thread-local storage in pocoman and that also is certainly wrong right now, not sure how serious it is.  The function passed to CreateThread immediately calls TlsSetValue, probably to stash some sort of "current state" object.

The way this works in general in Windows is the fs register is supposed points at the current thread's TEB, which then holds things like thread-local vars.  You can see where retrowin32's TEB is set up here, and in particular how it doesn't set anything up per thread:
https://github.com/evmar/retrowin32/blob/da79608b9d7b2e9c9ec1a9c518ffc145fe8c48cc/win32/src/winapi/kernel32/init.rs#L143

I think the way it should work is that instead whenever we create a thread we allocate a new TEB and set the fs_addr field in the CPU appropriately.  (And probably the place where the initial TEB is set up should use the same thing.)

Maybe I should extend this threads test first to exercise some of this...

**Comment by evmar** [comment]
Hm wait, the call at 0040c77d seems to be the thread function shutting down and is closing a handle found in the Tls, that seems very likely it.

**Comment by evmar** [comment]
I pushed a new thread.exe demonstrating the tls problem.

Right now it prints
```
thread=0 name="main" tls=1 i=0
thread=1 name="i_am_thread" tls=2 i=0
thread=0 name="main" tls=2 i=1
thread=1 name="i_am_thread" tls=2 i=1
thread=0 name="main" tls=2 i=2
thread=0 name="main" tls=2 i=3
thread=1 name="i_am_thread" tls=2 i=2
```

But if you look at the code, the tls values it prints should flip between 1/2 depending on which thread is running.

**Comment by evmar** [comment]
With https://github.com/evmar/retrowin32/commit/8c1713aff5eedd229aaf1319adb5d96801ae27c2 it now plays "I am pocoman" audio on startup.  Might get annoying, we can put it behind a flag if so!

**Comment by LinusU** [comment]
> With [8c1713a](https://github.com/evmar/retrowin32/commit/8c1713aff5eedd229aaf1319adb5d96801ae27c2) it now plays "I am pocoman" audio on startup. Might get annoying, we can put it behind a flag if so!

That's amazing!! 🤩 

Although it seems like the audio then underflows and crashes the entire application 😅 

```text
WARN cli/src/sdl.rs:319 audiobuf underflow
thread '<unnamed>' panicked at cli/src/sdl.rs:315:34:
range start index 44544 out of range for slice of length 44100
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception
zsh: abort      cargo run -p retrowin32 -F x86-emu,sdl -- --win32-trace '*' PocoMan.exe
```

**Comment by evmar** [comment]
Oh no!  I pushed another commit to disable it by default until I have it all working, sorry!

**Comment by evmar** [comment]
I added a `--audio` flag to the command line, and verified that after clicking through the first screen audio continues to work on the map if you click around.  I think with StretchBlt and some keyboard support this would be pretty solid.

**Comment by evmar** [comment]
The bitmap code is still gross but I made it a lot less gross in https://github.com/evmar/retrowin32/commit/af32dd4fa1c63638c8dfae5d23db5c2a2e5c85c2 , with a special eye to making StretchBlt easy to implement.

**Comment by evmar** [comment]
<img width="655" alt="image" src="https://github.com/user-attachments/assets/819eef94-3393-4e3e-a811-e8e84ada7bc4">

**Comment by evmar** [comment]
<img width="422" alt="image" src="https://github.com/user-attachments/assets/b86e79b7-3c6e-4899-a31c-93e77ca4f4fa">

sample program in exe/rust/bin/dib.rs that runs some of these functions

**Comment by evmar** [comment]
oh and i can run it in wine to compare!

<img width="268" alt="image" src="https://github.com/user-attachments/assets/4c34c616-3119-454c-8334-14858370a5d6">

**Comment by evmar** [comment]
https://github.com/evmar/retrowin32/commit/ccdac7115cf39068048feb93a9ac7ed180113a6a

<img width="656" alt="image" src="https://github.com/user-attachments/assets/44708f60-a5a0-4852-893e-f8657708786b">

**Comment by evmar** [comment]
Implemented some missing file stuff on the web site, now runs in my browser!

<img width="768" alt="image" src="https://github.com/user-attachments/assets/2142f508-4e1d-4d1e-88bf-a68bb96bf195">

**Comment by mateli** [comment]
An excellent first application to get running in retrowin32. Does this game have any networking or does it just import InternetOpenA for fun?

Perhaps filling missing functions with null pointers isn't a good idea. Better to link them to a missing function handler that does something more graceful. 

Running installers often fails even in wine. Building some tooling that can extract files from common installers would be useful. Often the main installer is just a self extracting archive of some kind. I ran into one that were encrypted with the encryption key as an embedded resource just to make extraction more difficult for some reason. This is probably not a one time occurrence, I am guessing that some decently popular install creator does this.

I think that this is a better way to install applications than to make retrowin32 capable of running the installer. First of all we have no control over what an installer does, they are prone to very bad behavior. Right now that isn't much of a problem but if retrowin32 catches on and are used to install and run multiple applications installer are a good way to mess up the registry, the filesystem etc. 

Making people depend on wine to extract the application is a good idea so instead lets analyze how this installer works. Then let's do a tool that identifies the type of installer and extracts the appropriate data into a package format that retrowin32 can use to run the application. It should be generic enough so for each application we support we can easily extend it. When retrowin32 starts with a known installer it should not be run as a win32 application but instead passed on to the tool and after extraction retrowin32 can start the actual application.

**Comment by LinusU** [comment]
> An excellent first application to get running in retrowin32. Does this game have any networking or does it just import InternetOpenA for fun?

I believe that it was for checking the latest version or something similar. Nothing that's needed to actually run the game...
